var express = require('express');
var router = express.Router();

const glossary_list = [
  { 'id': 1, 'Term': 'Agile Methodology', 'Description': 'Agile Methodology is a type of project management process, mainly used for software development, where demands and solutions evolve through the collaborative effort of self-organizing and cross-functional teams.', 'reference': 'Highsmith, J., & Cockburn, A. (2001). Agile software development: The business of innovation. Computer, 34(9), 120–127.' },
  { 'id': 2, 'Term': 'DevOps', 'Description': 'DevOps is a set of practices that combines software development and IT operations. It aims to shorten the system development life cycle and provide continuous delivery with high software quality.', 'reference': 'Loukides, M. (2012). What is DevOps? O\'Reilly Media.' },
  { 'id': 3, 'Term': 'Cloud Computing', 'Description': 'Cloud computing refers to the on-demand availability of computer system resources, especially data storage and computing power, without direct active management by the user.', 'reference': 'Mell, P., & Grance, T. (2011). The NIST definition of cloud computing. National Institute of Standards and Technology.' },
  { 'id': 4, 'Term': 'Microservices', 'Description': 'Microservices, or the microservices architectural style, is an approach to developing a single application as a suite of small services, each running its own process and communicating with lightweight mechanisms.', 'reference': 'Lewis, J., & Fowler, M. (2014). Microservices. https://martinfowler.com/articles/microservices.html' },
  { 'id': 5, 'Term': 'Command Line Interfaces (CLI)', 'Description': 'CLI is a means of interacting with a computer program where the user issues commands in the form of successive lines of text (command lines).', 'reference': 'Ritchie, D. M., & Thompson, K. (1974). The UNIX time-sharing system. Communications of the ACM, 17(7), 365-375.' },
  { 'id': 6, 'Term': 'Testing', 'Description': 'Testing is an empirical investigation conducted to provide stakeholders with information about the quality of the software product or service under test.', 'reference': 'Myers, G. J., Badgett, T., Thomas, T. M., & Sandler, C. (2004). The art of software testing. John Wiley & Sons.' },
  { 'id': 7, 'Term': 'Continuous Deployment', 'Description': 'Continuous Deployment is a software engineering approach in which software functionalities are delivered frequently through automated deployments.', 'reference': 'Fitzgerald, B., & Stol, K. J. (2017). Continuous software engineering: A roadmap and agenda. Journal of Systems and Software, 123, 176-189.' },
  { 'id': 8, 'Term': 'Continuous Integration', 'Description': 'Continuous Integration is a development practice that requires developers to integrate code into a shared repository several times a day.', 'reference': 'Duvall, P. M., Matyas, S. M., & Glover, A. (2007). Continuous integration: improving software quality and reducing risk. Pearson Education.' },
  { 'id': 9, 'Term': 'Behavior-Driven Design (BDD)', 'Description': 'BDD is an Agile software development process that encourages collaboration among developers, QA and non-technical or business participants in a software project.', 'reference': 'Adzic, G. (2011). Specification by example: How successful teams deliver the right software. Manning Publications Co.' },
  { 'id': 10, 'Term': 'Test-Driven Design (TDD)', 'Description': 'TDD is a software development process that relies on the repetition of a very short development cycle: first the developer writes an automated test case that defines a desired improvement or new function, then produces code to pass that test, and finally refactors the new code to acceptable standards.', 'reference': 'Beck, K. (2003). Test-driven development: by example. Addison-Wesley Professional.' },

  { 'id': 11, 'Term': 'Infrastructure as Code', 'Description': 'The process of managing and provisioning computer infrastructure through code and automation is known as infrastructure as code (IaC). Version control, consistency, and scalability are made possible by treating infrastructure configurations as software.', 'reference': 'AWS Documentation - https://aws.amazon.com/devops/infrastructure-as-code/' },
  { 'id': 12, 'Term': 'Virtualized Hardware', 'Description': 'The term virtualized hardware describes the application of virtualization technologies to produce several virtual machines running on a single physical server, enabling effective resource efficiency, isolation, and adaptability in managing computing resources.', 'reference': 'Oracle Virtualization - https://www.oracle.com/virtualization/what-is-server-virtualization.html)' },
  { 'id': 13, 'Term': 'Port Mapping', 'Description': 'Port mapping is a networking technique that enables communication with external devices or services by connecting a particular port of a host or container with a service that is executing on that host or container.', 'reference': 'Docker Documentation - https://docs.docker.com/config/containers/container-networking/)' },
  { 'id': 14, 'Term': 'Bridge Network', 'Description': 'A bridge network is a kind of network that links different containers on the same host, allowing them to communicate via a common network interface. It enables smooth communication between containers and the host by enabling them to run on the same network.', 'reference': 'Docker Documentation - https://docs.docker.com/network/bridge/' },
  { 'id': 15, 'Term': 'Overlay Network', 'Description': 'An overlay network is a network that connects many Docker hosts and enables communication between containers running on various hosts as though they were on the same network. It is appropriate for distributed applications since it allows container-to-container communication between hosts.', 'reference': 'Docker Documentation - https://docs.docker.com/network/overlay/' },
  { 'id': 16, 'Term': 'Macvlan Network', 'Description': 'A macvlan network enables a container to have a distinct MAC address, which makes it seem like a different physical device on the network. It makes it possible for containers to communicate directly with external networks without the burden of network address translation (NAT).', 'reference': 'Docker Documentation - https://docs.docker.com/network/macvlan/' },
  { 'id': 17, 'Term': 'Configuration Management', 'Description': 'The process of controlling and preserving the consistency of a system\'s hardware, software, and documentation throughout its lifecycle is known as configuration management.', 'reference': 'ITIL (Information Technology Infrastructure Library) - Configuration Management. Retrieved from https://www.axelos.com/itil-update-2018/itil-articles/what-is-configuration-management' },
  { 'id': 18, 'Term': 'Change Management', 'Description': 'To assure effective outcomes and reduce disruptions, change management is an organized way to planning, implementing, and tracking changes to organizations, processes, or systems.', 'reference': 'Prosci - Change Management. Retrieved from https://www.prosci.com/change-management' },
  { 'id': 19, 'Term': 'Continuous Monitoring', 'Description': 'Throughout the development, testing, and production phases of a software application, continuous monitoring in DevOps refers to the continual process of gathering and evaluating real-time data regarding the performance, security, and quality of the software.', 'reference': 'The DevOps Handbook: How to Create World-Class Agility, Reliability, and Security in Technology Organizations" by Gene Kim, Patrick Debois, John Willis, and Jez Humble.' },
  { 'id': 20, 'Term': 'Containerization', 'Description': 'Applications and their dependencies are packaged into small, isolated containers as part of the DevOps process known as containerization to enable efficient and consistent deployment across various environments.', 'reference': 'Docker Documentation - https://docs.docker.com/get-started/overview/' },
  { 'id': 21, 'Term': 'API gateway', 'Description': 'An API Gateway is a server that acts as a middleman, directing client queries to the proper services. For microservices designs, it provides capabilities like security, rate limitation, caching, and logging, centralizing these issues.', 'reference': 'https://aws.amazon.com/api-gateway/' },
  { 'id': 22, 'Term': 'Docker Compose', 'Description': 'Multi-container Docker applications can be created and executed using Docker Compose. You can set up services, networks, and volumes with a docker-compose.yml file, allowing you to launch and control a whole application stack with a single command.', 'reference': 'https://docs.docker.com/compose/' },
  { 'id': 23, 'Term': 'Agile Approach', 'Description': 'Agile is a project management and product development approach that prioritizes flexibility, collaboration, and customer feedback. It involves iterative work cycles, known as sprints, and emphasizes adaptability to changing requirements.', 'reference': 'https://agilemanifesto.org/' },
  { 'id': 24, 'Term': 'Multi-container', 'Description': 'Multi-container refers to applications that are split into multiple containerized services, each handling a particular function, in the context of Docker and containerization. Better scaling, isolation, and management of each service are made possible by this method.', 'reference': 'https://docs.docker.com/compose/' },
  { 'id': 25, 'Term': 'YAML', 'Description': 'All computer languages can use YAML (YAML Ain\'t Markup Language), a human-readable data serialization standard that is frequently used for configuration files, deployment scripts, and data interchange. It is a well-liked option for jobs like specifying container orchestrations or expressing infrastructure as code because to its simplicity and readability.', 'reference': 'https://yaml.org/' },
  { 'id': 26, 'Term': 'Docker Volumes', 'Description': 'In Docker, volumes are used to store data independently of a container\'s lifecycle, allowing data retention even if a container is removed. They facilitate data persistence and sharing across containers.', 'reference': 'https://docs.docker.com/storage/volumes/' },
  { 'id': 27, 'Term': 'Shell script', 'Description': 'Shell scripts are sequences of commands written for shell interpreters, allowing automation and combination of multiple tasks. They\'re prevalent in UNIX-like systems.', 'reference': 'https://tldp.org/LDP/abs/html/' },
  { 'id': 28, 'Term': 'Kubernetes', 'Description': 'It is an open-source platform called Kubernetes, also referred to as K8s, is created to simplify the deployment, scaling, and management of containerized applications. It offers tools for orchestration, service discovery, and load balancing, and organizes containers into "pods".', 'reference': 'https://kubernetes.io/docs/home/' },
  { 'id': 29, 'Term': 'Blub', 'Description': 'A group of binary data that is stored as a single entity is referred to as a blob (Binary Large Object). Large volumes of data, such files or photos, that don\'t cleanly fit into conventional relational data types are stored in databases using this technique.', 'reference': 'https://en.wikipedia.org/wiki/Binary_large_object' },
  { 'id': 30, 'Term': 'Cluster Storage', 'Description': 'It is a storage system that offers data storage services to a group of computers and these systems are frequently employed in high-availability and high-performance computing environments. Cluster storage disperses data among several devices, frequently dispersed across various locations, as opposed to depending on a single storage device. Performance, scalability, and fault tolerance are improved by this distribution. Cluster storage solutions might be either software- or hardware-based, or perhaps both.', 'reference': 'https://www.techtarget.com/searchstorage/magazineContent/The-benefits-of-clustered-storage' },
  { 'id': 31, 'Term': 'Cypress', 'Description': 'Cypress is a web application end-to-end testing framework built on JavaScript. It runs directly in the browser, unlike many testing tools, and provides real-time reloads, a time-traveling debugger, and automatic waiting. It\'s a well-liked substitute for selenium.', 'reference': 'Official Website: https://www.cypress.io/' },
  { 'id': 32, 'Term': 'Orchestration pipeline', 'Description': 'The automatic coordination, management, and configuration of sophisticated computer systems, services, and middleware is referred to as an orchestration pipeline. The process of automating several tasks in the context of DevOps is used to launch, manage, and scale applications.', 'reference': 'https://www.redhat.com/en/topics/automation/what-is-orchestration' },
  { 'id': 33, 'Term': 'Cluster', 'Description': 'In computing, a cluster is a collection of computers or servers that cooperate and are regarded as a single system. By enabling load balancing, fault tolerance, and parallel processing, clusters outperform single computers in terms of performance and availability.', 'reference': 'https://www.techtarget.com/search/query?q=cluster' },
  { 'id': 34, 'Term': 'Azure Load Balancer', 'Description': 'Microsoft Azure\'s Azure Load Balancer distributes incoming traffic among healthy virtual machines (VMs) in a cloud infrastructure to offer load balancing and ensure high availability. It supports both the TCP and UDP protocols and can be used in both inbound and outbound applications.', 'reference': 'https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-overview' },
  { 'id': 35, 'Term': 'Command-line arguments', 'Description': 'When a program is run from the command line or terminal, it receives inputs known as command-line arguments. Users can set options or provide data using these arguments without having to change the program\'s source code. These arguments are available to the application as an array of strings in various programming languages.', 'reference': 'https://en.wikipedia.org/wiki/Command-line_interface#Arguments' },
  { 'id': 36, 'Term': 'Canary Release', 'Description': 'To roll out modifications to a smaller group of users or servers before a full deployment, as explained. It assists in identifying possible problems before they spread to the full user base.', 'reference': 'https://martinfowler.com/bliki/CanaryRelease.html' },
  { 'id': 37, 'Term': 'Immutable Infrastructure', 'Description': 'An infrastructure approach where servers are deployed and never updated after that. New servers are constructed from a shared image, and the old ones are removed if anything has to be updated, corrected, or modified in any way.', 'reference': 'https://www.hashicorp.com/resources/what-is-mutable-vs-immutable-infrastructure' },
  { 'id': 38, 'Term': 'Service Mesh', 'Description': 'In microservice architectures, a specific infrastructure layer is responsible for managing service-to-service communication. It offers functions including security, load balancing, service discovery, and traffic management.', 'reference': 'https://buoyant.io/service-mesh-manifesto' },
  { 'id': 39, 'Term': 'Webhook', 'Description': 'A technique for enhancing or changing a web pages or application\'s behaviour via customized callbacks. Third-party users and programmers may maintain, alter, and manage these callbacks.', 'reference': 'https://sendgrid.com/blog/whats-webhook/' },
  { 'id': 40, 'Term': 'Test fixture', 'Description': 'For the purpose of conducting tests, a test fixture creates a defined environment or state. It guarantees that tests have a well-defined and consistent starting point, making test results predictable. In addition to databases, test fixtures may also include files, mock objects, configurations, or any other setup necessary for testing.', 'reference': 'https://docs.pytest.org/en/6.2.x/fixture.html' },
  { 'id': 41, 'Term': 'Regression testing', 'Description': 'Regression testing is the practice of ensuring that recently made modifications to previously built and tested software don\'t affect its functionality. It makes sure that recent code modifications have not negatively impacted already-existing functionalities. Regression testing can be done manually or automatically, however because it is repetitive, automation is frequently used for productivity.', 'reference': 'Myers, G. J., Sandler, C., & Badgett, T. (2011). The Art of Software Testing. John Wiley & Sons p-85 https://doi.org/10.1002/stvr.32' },
  { 'id': 42, 'Term': 'Log Aggregation', 'Description': 'In order to make monitoring, analysis, and troubleshooting easier, a technique known as log aggregation involves gathering and consolidating log events from several sources into a single area.', 'reference': 'Datadog, “Log Aggregation: What It Is & How It Works | Datadog,” Log Aggregation: What It Is & How It Works, Aug. 03, 2021. https://www.datadoghq.com/knowledge-center/log-aggregation/' },
  { 'id': 43, 'Term': 'Elasticsearch', 'Description': 'Based on the Lucene library, Elasticsearch is a distributed, RESTful search and analytics engine. It offers a scalable search solution and has the capacity to process huge amounts of data almost instantly. Due to its quick indexing and search capabilities, Elasticsearch is frequently used for log and event data analysis.', 'reference': 'Elasticsearch: The Official Distributed Search & Analytics Engine,” Elastic. https://www.elastic.co/elasticsearch/' },
  { 'id': 44, 'Term': 'Kibana', 'Description': 'Elasticsearch has a visualization and user interface layer called Kibana. It offers a web-based interface for viewing Elasticsearch data in a range of visual representations, including graphs, tables, and maps. Kibana also provides tools for exploring data, monitoring Elasticsearch clusters, and creating dashboards.', 'reference': 'Elasticsearch: The Official Distributed Search & Analytics Engine,” Elastic. https://www.elastic.co/elasticsearch/' },
  { 'id': 45, 'Term': 'Principle of least privilege', 'Description': 'A security rule that states individuals, systems, or processes should only have the minimal access necessary to carry out their functions and nothing more. This reduces potential harm in the event that an entity is compromised or commits a mistake.', 'reference': 'Wikipedia Contributors, “Principle of least privilege,” Wikipedia, Jul. 10, 2019. https://en.wikipedia.org/wiki/Principle_of_least_privilege' },
  { 'id': 46, 'Term': 'Deployment Configuration', 'Description': 'A group of specifications, options, and settings applied when delivering software or applications to a specific environment. It outlines the installation process for software, the version to use, environment-specific parameters, and any other information required for a successful deployment.', 'reference': 'Deployments,” Kubernetes.https://kubernetes.io/docs/concepts/workloads/controllers/deployment/' },
  { 'id': 47, 'Term': 'Site reliability engineering', 'Description': 'A discipline with the objective of developing highly scalable and dependable software systems by integrating elements of software engineering into IT operations. SRE, which was developed at Google, has a strong emphasis on automating infrastructure, gauging reliability using Service Level Objectives (SLOs), and balancing release velocity with system reliability using error budgets.', 'reference': '“Site reliability engineering,” Wikipedia, Oct. 22, 2021. https://en.wikipedia.org/wiki/Site_reliability_engineering' },
  { 'id': 48, 'Term': 'Service Level Objective (SLO)', 'Description': 'A desired degree of performance or accessibility for a good or service that an organization aspires to provide. It acts as a benchmark for the intended level of service dependability.', 'reference': 'Atlassian, “SLA vs. SLO vs. SLI - Differences,” Atlassian. https://www.atlassian.com/incident-management/kpis/sla-vs-slo-vs-sli' },
  { 'id': 49, 'Term': 'Service Level Indicator (SLI)', 'Description': 'a metric or measurement that is used to express the system\'s performance or level of service at the moment. Data from SLIs can be compared against SLOs to ascertain whether performance goals are being reached.', 'reference': 'Atlassian, “SLA vs. SLO vs. SLI - Differences,” Atlassian. https://www.atlassian.com/incident-management/kpis/sla-vs-slo-vs-sli' },
  { 'id': 50, 'Term': 'Pod', 'Description': 'The smallest and most basic deployable device that holds one or more containers is a pod. A pod\'s containers may readily connect with one another and share information because they all have the same IP address, port space, and storage.', 'reference': '“Pods,” Kubernetes. https://kubernetes.io/docs/concepts/workloads/pods/' }
  
];





/* GET home page. */
router.get('/', function (req, res, next) {
  res.render('index', { title: 'SIT722 Glossary', glossary: glossary_list });
});

module.exports = router;

